"""
Synthetic dataset generation for synfit.

Config dicts (from config.json) are the source of truth.
CSVs are derived artifacts regenerated by scripts/generate_seed_datasets.py.

A set of ready-made scenarios ships with the package — clean and noisy
single-drug curves, an activation curve, additive and synergistic matrices,
a Loewe sham (a drug combined with itself). Each has a ``config.json``
recording the exact generating parameters, so the ground truth of every
fit is known. Reach them with :func:`list_scenarios`, :func:`scenario_dir`
and :func:`scenario_config`.
"""
import json
from importlib.resources import as_file, files
from pathlib import Path

import numpy as np
import pandas as pd

from .hill import hill_curve, calculate_concentration_series
from .bliss import bliss_independence
from .loewe import loewe_reference


def _scenarios_root() -> Path:
    """Filesystem path of the shipped ``scenarios`` directory.

    ``synfit`` installs as a plain directory, so the package resource is
    always a real path; ``as_file`` keeps that honest if it ever is not.
    """
    with as_file(files(__package__) / "scenarios") as path:
        return path


SCENARIOS_DIR: Path = _scenarios_root()


def list_scenarios() -> list[str]:
    """Names of the scenarios shipped with the package, sorted."""
    if not SCENARIOS_DIR.is_dir():
        return []
    return sorted(
        d.name for d in SCENARIOS_DIR.iterdir()
        if d.is_dir() and (d / "config.json").is_file()
    )


def scenario_dir(name: str) -> Path:
    """Directory of one shipped scenario: its ``config.json`` and CSVs.

    Single-drug scenarios hold one ``<name>.csv``; matrix scenarios hold
    one ``rep*.csv`` per replicate.
    """
    path = SCENARIOS_DIR / name
    if not (path / "config.json").is_file():
        raise KeyError(f"Unknown scenario: {name!r}")
    return path


def scenario_config(name: str) -> dict:
    """Generating parameters of one shipped scenario."""
    return json.loads((scenario_dir(name) / "config.json").read_text())


def _apply_noise(y_true, noise_model: str, noise_params: dict, rng: np.random.Generator):
    """Apply noise to a true response value or array.

    Two families:

    ``"gaussian"`` — additive Gaussian with σ²(μ) = a + b·μ + c·μ² evaluated
    at the true generating mean (not the fitter's lower-asymptote anchor).
    The homoscedastic case is just ``b = c = 0``. Generation keeps the
    true-μ polynomial so synthetic data match a known process; the fitter
    anchors the same coefficients at ``m = min(effect_0, effect_inf)``.

    ``"lognormal"`` — multiplicative: ``y · exp(N(0, σ_log))``. Strictly
    positive, skewed; not a special case of the gaussian polynomial.
    """
    if noise_model == "lognormal":
        sigma = noise_params["sigma_log"]
        return y_true * np.exp(rng.normal(0, sigma, size=np.shape(y_true)))
    if noise_model == "gaussian":
        a = noise_params.get("a", 0.0)
        b = noise_params.get("b", 0.0)
        c = noise_params.get("c", 0.0)
        y_arr = np.asarray(y_true)
        var = np.maximum(a + b * y_arr + c * y_arr ** 2, 0.0)
        sigma = np.sqrt(var)
        return y_true + rng.normal(0, 1.0, size=np.shape(y_true)) * sigma
    raise ValueError(f"Unknown noise_model: {noise_model!r}")


def _parse_noise_config(config: dict) -> tuple[str, dict]:
    """Extract noise_model and its parameters from a config dict.

    Two families::

        "noise_model": "lognormal",
        "noise_sigma_log": 0.05

        "noise_model": "gaussian",
        "noise_var_a": 1e-3,
        "noise_var_b": 0.0,
        "noise_var_c": 0.0

    Legacy ``noise_sigma`` (homoscedastic stddev) is accepted and converted
    to ``var_a = σ²`` when the polynomial coefficients aren't supplied.
    """
    model = config.get("noise_model", "gaussian")
    if model == "lognormal":
        return model, {"sigma_log": config.get("noise_sigma_log", 0.05)}
    if model == "gaussian":
        has_poly = any(k in config for k in ("noise_var_a", "noise_var_b", "noise_var_c"))
        if has_poly:
            return model, {
                "a": float(config.get("noise_var_a", 0.0)),
                "b": float(config.get("noise_var_b", 0.0)),
                "c": float(config.get("noise_var_c", 0.0)),
            }
        sigma = float(config.get("noise_sigma", 0.05))
        return model, {"a": sigma * sigma, "b": 0.0, "c": 0.0}
    raise ValueError(f"Unknown noise_model: {model!r}")


def generate_single_drug(config: dict, rng: np.random.Generator | None = None) -> pd.DataFrame:
    """
    Generate a synthetic single-drug dose-response DataFrame.

    Returns DataFrame with columns: concentration, y, replicate.

    config keys:
        hill_params:         {c50, hill, effect_0, effect_inf}
        concentration_series: {initial_conc, fold_dilutions, length, has_zero}
        n_replicates:        int
        noise_model:         "lognormal" (default) | "gaussian"
        noise_sigma_log:     float (lognormal: CV ≈ sigma_log)
        noise_sigma:         float (gaussian: additive std dev — legacy alias for var_a = σ²)
        noise_var_a / b / c: floats for σ²(μ) = a + b·μ + c·μ² under gaussian
                             (true-μ polynomial; see ``_apply_noise``)
        outliers:            list of {replicate, concentration_index, value}  (optional)
        seed:                int (used if rng not provided)
    """
    if rng is None:
        rng = np.random.default_rng(config.get("seed", 42))

    p = config["hill_params"]
    cs = config["concentration_series"]
    concs = calculate_concentration_series(
        initial_conc=cs["initial_conc"],
        fold_dilutions=cs["fold_dilutions"],
        length=cs["length"],
        has_zero=cs.get("has_zero", True),
    )

    noise_model, noise_params = _parse_noise_config(config)
    n_replicates = config.get("n_replicates", 3)
    rep_labels = [chr(65 + i) for i in range(n_replicates)]  # A, B, C, ...

    rows = []
    for rep in rep_labels:
        for conc in concs:
            if conc == 0:
                y_true = p["effect_0"]  # zero concentration → uninhibited response
            else:
                y_true = hill_curve(conc, c50=p["c50"], hill=p["hill"],
                                    effect_0=p["effect_0"], effect_inf=p["effect_inf"])
            y_obs = float(_apply_noise(y_true, noise_model, noise_params, rng))
            rows.append({"concentration": conc, "y": float(y_obs), "replicate": rep})

    df = pd.DataFrame(rows)

    # Inject outliers: override specific (replicate, concentration_index) with fixed value
    for outlier in config.get("outliers", []):
        rep = outlier["replicate"]
        conc_idx = outlier["concentration_index"]
        value = outlier["value"]
        target_conc = concs[conc_idx]
        mask = (df["replicate"] == rep) & (df["concentration"] == target_conc)
        df.loc[mask, "y"] = value

    return df


def generate_matrix(
    config: dict, rng: np.random.Generator | None = None
) -> tuple[list[np.ndarray], np.ndarray, np.ndarray]:
    """
    Generate synthetic drug-drug interaction matrix replicates.

    Returns ``(replicates, conc_horizontal, conc_vertical)``: one 2D array
    per replicate (n_vertical × n_horizontal), and the concentration vector
    of each axis.

    config keys:
        horizontal_drug:  {c50, hill, concentration_series: {initial_conc, fold_dilutions, length}}
        vertical_drug:    same
        effect_0, effect_inf:      float
        n_replicates:     int
        noise_model:      "lognormal" (default) | "gaussian"
        noise_sigma_log:  float (lognormal: CV ≈ sigma_log)
        noise_sigma:      float (gaussian: additive std dev — legacy alias for var_a = σ²)
        noise_var_a / b / c: floats for σ²(μ) = a + b·μ + c·μ² under gaussian
                             (true-μ polynomial; see ``_apply_noise``)
        reference_model:  "bliss" (default) | "loewe" — which null-hypothesis
                          surface to generate before applying noise. Use "loewe"
                          to build Loewe-additive (CI = 1) matrices for testing
                          the combination index; equal `hill` on both drugs is
                          recommended in that case since unequal-slope Loewe
                          is theoretically shaky.
        synergy_factor:   float  (0 = no deviation from the chosen reference;
                                  positive = extra inhibition on top of the
                                  reference surface; negative = antagonism).
                                  A potency shift: each drug acts at
                                  ``c · (1 + s·f_partner)``, where ``f_partner``
                                  ∈ [0, 1] is the other drug's fractional
                                  effect at its own concentration — so a
                                  partner at full effect makes the drug
                                  ``(1 + s)``-fold more potent. Zero wherever
                                  either drug is absent: the single-drug edges
                                  stay exactly on the configured Hill curves.
                                  Both Bliss and Loewe see the shift. Requires
                                  ``s > −1``.
        seed:             int
    """
    if rng is None:
        rng = np.random.default_rng(config.get("seed", 42))

    def _concs(drug_cfg):
        cs = drug_cfg["concentration_series"]
        return calculate_concentration_series(
            initial_conc=cs["initial_conc"],
            fold_dilutions=cs["fold_dilutions"],
            length=cs["length"],
            has_zero=cs.get("has_zero", False),
        )

    h = config["horizontal_drug"]
    v = config["vertical_drug"]
    conc_hor = _concs(h)
    conc_ver = _concs(v)
    effect_0 = config.get("effect_0", 1.0)
    effect_inf = config.get("effect_inf", 0.0)
    noise_model, noise_params = _parse_noise_config(config)
    synergy_factor = config.get("synergy_factor", 0.0)
    if synergy_factor <= -1.0:
        raise ValueError(
            f"synergy_factor must be > -1 (got {synergy_factor}); at -1 a "
            "fully effective partner drives the effective concentration to 0"
        )
    n_replicates = config.get("n_replicates", 3)
    reference_model = config.get("reference_model", "bliss")

    if reference_model == "bliss":
        reference = bliss_independence
    elif reference_model == "loewe":
        reference = loewe_reference
    else:
        raise ValueError(
            f"Unknown reference_model: {reference_model!r} "
            "(expected 'bliss' or 'loewe')"
        )
    drug_params = dict(
        c50_hor=h["c50"], c50_ver=v["c50"],
        hill_hor=h["hill"], hill_ver=v["hill"],
        effect_0=effect_0, effect_inf=effect_inf,
    )

    if synergy_factor == 0.0 or effect_0 == effect_inf:
        surface = reference(conc_hor, conc_ver, **drug_params)
    else:
        # Interaction as a potency shift: each drug acts at an effective
        # concentration raised by the other drug's fractional effect. The
        # shift is zero wherever the partner is absent, so the single-drug
        # edges stay on the configured Hill curves. (A shift of the
        # reference level alone, u − s·u(1−u), moved the edges too: it read
        # as weak antagonism against an observed-edge Bliss reference and
        # as no interaction at all under Loewe, which is invariant to any
        # remapping of the response axis.)
        scale = effect_0 - effect_inf
        effect_hor = 1 - (hill_curve(conc_hor, c50=h["c50"], hill=h["hill"],
                                     effect_0=effect_0, effect_inf=effect_inf) - effect_inf) / scale
        effect_ver = 1 - (hill_curve(conc_ver, c50=v["c50"], hill=v["hill"],
                                     effect_0=effect_0, effect_inf=effect_inf) - effect_inf) / scale
        eff_hor = conc_hor[np.newaxis, :] * (1 + synergy_factor * effect_ver[:, np.newaxis])
        eff_ver = conc_ver[:, np.newaxis] * (1 + synergy_factor * effect_hor[np.newaxis, :])
        surface = np.empty((conc_ver.size, conc_hor.size))
        for i, j in np.ndindex(surface.shape):
            surface[i, j] = reference(
                eff_hor[i, j:j + 1], eff_ver[i:i + 1, j], **drug_params,
            )[0, 0]

    replicates = []
    for _ in range(n_replicates):
        rep = _apply_noise(surface, noise_model, noise_params, rng)
        replicates.append(rep)

    return replicates, conc_hor, conc_ver
