"""
Synthetic dataset generation for synfit.

Config dicts (from config.json) are the source of truth.
CSVs are derived artifacts regenerated by scripts/generate_seed_datasets.py.

A set of ready-made scenarios ships with the package — clean and noisy
single-drug curves, an activation curve, additive and synergistic matrices,
a Loewe sham (a drug combined with itself). Each has a ``config.json``
recording the exact generating parameters, so the ground truth of every
fit is known. Reach them with :func:`list_scenarios`, :func:`scenario_dir`
and :func:`scenario_config`.
"""
import json
from importlib.resources import as_file, files
from pathlib import Path

import numpy as np
import pandas as pd

from .hill import hill_curve, calculate_concentration_series
from .bliss import bliss_independence
from .loewe import loewe_reference


def _scenarios_root() -> Path:
    """Filesystem path of the shipped ``scenarios`` directory.

    ``synfit`` installs as a plain directory, so the package resource is
    always a real path; ``as_file`` keeps that honest if it ever is not.
    """
    with as_file(files(__package__) / "scenarios") as path:
        return path


SCENARIOS_DIR: Path = _scenarios_root()


def list_scenarios() -> list[str]:
    """Names of the scenarios shipped with the package, sorted."""
    if not SCENARIOS_DIR.is_dir():
        return []
    return sorted(
        d.name for d in SCENARIOS_DIR.iterdir()
        if d.is_dir() and (d / "config.json").is_file()
    )


def scenario_dir(name: str) -> Path:
    """Directory of one shipped scenario: its ``config.json`` and CSVs.

    Single-drug scenarios hold one ``<name>.csv``; matrix scenarios hold
    one ``rep*.csv`` per replicate.
    """
    path = SCENARIOS_DIR / name
    if not (path / "config.json").is_file():
        raise KeyError(f"Unknown scenario: {name!r}")
    return path


def scenario_config(name: str) -> dict:
    """Generating parameters of one shipped scenario."""
    return json.loads((scenario_dir(name) / "config.json").read_text())


def _apply_noise(y_true, noise_model: str, noise_params: dict, rng: np.random.Generator):
    """Apply noise to a true response value or array.

    Two families:

    ``"gaussian"`` — additive Gaussian with σ²(μ) = a + b·μ + c·μ² evaluated
    at the true generating mean (not the fitter's lower-asymptote anchor).
    The homoscedastic case is just ``b = c = 0``. Generation keeps the
    true-μ polynomial so synthetic data match a known process; the fitter
    anchors the same coefficients at ``m = min(effect_0, effect_inf)``.

    ``"lognormal"`` — multiplicative: ``y · exp(N(0, σ_log))``. Strictly
    positive, skewed; not a special case of the gaussian polynomial.
    """
    if noise_model == "lognormal":
        sigma = noise_params["sigma_log"]
        return y_true * np.exp(rng.normal(0, sigma, size=np.shape(y_true)))
    if noise_model == "gaussian":
        a = noise_params.get("a", 0.0)
        b = noise_params.get("b", 0.0)
        c = noise_params.get("c", 0.0)
        y_arr = np.asarray(y_true)
        var = np.maximum(a + b * y_arr + c * y_arr ** 2, 0.0)
        sigma = np.sqrt(var)
        return y_true + rng.normal(0, 1.0, size=np.shape(y_true)) * sigma
    raise ValueError(f"Unknown noise_model: {noise_model!r}")


def _parse_noise_config(config: dict) -> tuple[str, dict]:
    """Extract noise_model and its parameters from a config dict.

    Two families::

        "noise_model": "lognormal",
        "noise_sigma_log": 0.05

        "noise_model": "gaussian",
        "noise_var_a": 1e-3,
        "noise_var_b": 0.0,
        "noise_var_c": 0.0

    Legacy ``noise_sigma`` (homoscedastic stddev) is accepted and converted
    to ``var_a = σ²`` when the polynomial coefficients aren't supplied.
    """
    model = config.get("noise_model", "gaussian")
    if model == "lognormal":
        return model, {"sigma_log": config.get("noise_sigma_log", 0.05)}
    if model == "gaussian":
        has_poly = any(k in config for k in ("noise_var_a", "noise_var_b", "noise_var_c"))
        if has_poly:
            return model, {
                "a": float(config.get("noise_var_a", 0.0)),
                "b": float(config.get("noise_var_b", 0.0)),
                "c": float(config.get("noise_var_c", 0.0)),
            }
        sigma = float(config.get("noise_sigma", 0.05))
        return model, {"a": sigma * sigma, "b": 0.0, "c": 0.0}
    raise ValueError(f"Unknown noise_model: {model!r}")


def generate_single_drug(config: dict, rng: np.random.Generator | None = None) -> pd.DataFrame:
    """
    Generate a synthetic single-drug dose-response DataFrame.

    Returns DataFrame with columns: concentration, y, replicate.

    config keys:
        hill_params:         {c50, hill, effect_0, effect_inf}
        concentration_series: {initial_conc, fold_dilutions, length, has_zero}
        n_replicates:        int
        noise_model:         "lognormal" (default) | "gaussian"
        noise_sigma_log:     float (lognormal: CV ≈ sigma_log)
        noise_sigma:         float (gaussian: additive std dev — legacy alias for var_a = σ²)
        noise_var_a / b / c: floats for σ²(μ) = a + b·μ + c·μ² under gaussian
                             (true-μ polynomial; see ``_apply_noise``)
        outliers:            list of {replicate, concentration_index, value}  (optional)
        seed:                int (used if rng not provided)
    """
    if rng is None:
        rng = np.random.default_rng(config.get("seed", 42))

    p = config["hill_params"]
    cs = config["concentration_series"]
    concs = calculate_concentration_series(
        initial_conc=cs["initial_conc"],
        fold_dilutions=cs["fold_dilutions"],
        length=cs["length"],
        has_zero=cs.get("has_zero", True),
    )

    noise_model, noise_params = _parse_noise_config(config)
    n_replicates = config.get("n_replicates", 3)
    rep_labels = [chr(65 + i) for i in range(n_replicates)]  # A, B, C, ...

    rows = []
    for rep in rep_labels:
        for conc in concs:
            if conc == 0:
                y_true = p["effect_0"]  # zero concentration → uninhibited response
            else:
                y_true = hill_curve(conc, c50=p["c50"], hill=p["hill"],
                                    effect_0=p["effect_0"], effect_inf=p["effect_inf"])
            y_obs = float(_apply_noise(y_true, noise_model, noise_params, rng))
            rows.append({"concentration": conc, "y": float(y_obs), "replicate": rep})

    df = pd.DataFrame(rows)

    # Inject outliers: override specific (replicate, concentration_index) with fixed value
    for outlier in config.get("outliers", []):
        rep = outlier["replicate"]
        conc_idx = outlier["concentration_index"]
        value = outlier["value"]
        target_conc = concs[conc_idx]
        mask = (df["replicate"] == rep) & (df["concentration"] == target_conc)
        df.loc[mask, "y"] = value

    return df


def generate_matrix(
    config: dict, rng: np.random.Generator | None = None
) -> tuple[list[np.ndarray], np.ndarray, np.ndarray]:
    """
    Generate synthetic drug-drug interaction matrix replicates.

    Returns ``(replicates, conc_horizontal, conc_vertical)``: one 2D array
    per replicate (n_vertical × n_horizontal), and the concentration vector
    of each axis.

    config keys:
        horizontal_drug:  {c50, hill, concentration_series: {initial_conc, fold_dilutions, length}}
        vertical_drug:    same
        effect_0, effect_inf:      float
        n_replicates:     int
        noise_model:      "lognormal" (default) | "gaussian"
        noise_sigma_log:  float (lognormal: CV ≈ sigma_log)
        noise_sigma:      float (gaussian: additive std dev — legacy alias for var_a = σ²)
        noise_var_a / b / c: floats for σ²(μ) = a + b·μ + c·μ² under gaussian
                             (true-μ polynomial; see ``_apply_noise``)
        reference_model:  "bliss" (default) | "loewe" — which null-hypothesis
                          surface to generate before applying noise. Use "loewe"
                          to build Loewe-additive (CI = 1) matrices for testing
                          the combination index; equal `hill` on both drugs is
                          recommended in that case since unequal-slope Loewe
                          is theoretically shaky.
        synergy_factor:   float  (0 = no deviation from the chosen reference;
                                  positive = extra inhibition on top of the
                                  reference surface; negative = antagonism).
                                  Applied to both models via the same
                                  normalised-response shift.
        seed:             int
    """
    if rng is None:
        rng = np.random.default_rng(config.get("seed", 42))

    def _concs(drug_cfg):
        cs = drug_cfg["concentration_series"]
        return calculate_concentration_series(
            initial_conc=cs["initial_conc"],
            fold_dilutions=cs["fold_dilutions"],
            length=cs["length"],
            has_zero=cs.get("has_zero", False),
        )

    h = config["horizontal_drug"]
    v = config["vertical_drug"]
    conc_hor = _concs(h)
    conc_ver = _concs(v)
    effect_0 = config.get("effect_0", 1.0)
    effect_inf = config.get("effect_inf", 0.0)
    noise_model, noise_params = _parse_noise_config(config)
    synergy_factor = config.get("synergy_factor", 0.0)
    n_replicates = config.get("n_replicates", 3)
    reference_model = config.get("reference_model", "bliss")

    if reference_model == "bliss":
        surface = bliss_independence(
            conc_hor, conc_ver,
            c50_hor=h["c50"], c50_ver=v["c50"],
            hill_hor=h["hill"], hill_ver=v["hill"],
            effect_0=effect_0, effect_inf=effect_inf,
        )
    elif reference_model == "loewe":
        surface = loewe_reference(
            conc_hor, conc_ver,
            c50_hor=h["c50"], c50_ver=v["c50"],
            hill_hor=h["hill"], hill_ver=v["hill"],
            effect_0=effect_0, effect_inf=effect_inf,
        )
    else:
        raise ValueError(
            f"Unknown reference_model: {reference_model!r} "
            "(expected 'bliss' or 'loewe')"
        )

    # Apply synergy: shift normalised response away from the reference, then rescale.
    if synergy_factor != 0.0:
        scale = effect_0 - effect_inf
        if scale != 0:
            surf_norm = (surface - effect_inf) / scale
            # synergy_factor > 0 → more inhibition (lower response)
            adjusted_norm = np.clip(
                surf_norm - synergy_factor * surf_norm * (1 - surf_norm), 0, 1
            )
            surface = effect_inf + adjusted_norm * scale

    replicates = []
    for _ in range(n_replicates):
        rep = _apply_noise(surface, noise_model, noise_params, rng)
        replicates.append(rep)

    return replicates, conc_hor, conc_ver
